Base Structure for V3 resources
dhvanilshah-tenable/pyTenable pull request #2
Opened 2021-11-16 06:18 UTC by ngaglani-tenable

- This PR contains the proposed base structure for code for v3 resources
- Current structure is something like
```
io/
   __init__.py
	v3/
            __init__.py
            base/
                endpoints/
	                uw.py
                iterators/
                schema/
	                analysis.py
	                exports.py
            assets.py
```

- Previous usage
```tio.assets.list()```
- Updated usage
```tio.v3.assets.list()```

2021-11-16 18:23 UTC, SteveMcGrath requested changes
Generally it appears that the assets.py was just lifted and placed here instead of being refactored to match updated code structures.  Refer to the exports PR for inspiration.

https://github.com/tenable/pyTenable/pull/463

2021-11-16 18:23 UTC, SteveMcGrath commented on tenable/io/__init__.py
> +        :doc:`Tenable.io v3 APIs`.
docstring doesn't link to the appropriate doc page.

2021-11-16 18:23 UTC, SteveMcGrath commented on tenable/io/v3/__init__.py
> +        The interface object for the Assets API's
docstring doesn't link to the appropriate doc page.

2021-11-16 18:23 UTC, SteveMcGrath commented on tenable/io/v3/__init__.py
> +===========
docstring doesn't include the relevant toctree and define what the v3 API are.

2021-11-16 18:23 UTC, SteveMcGrath commented on tenable/io/v3/assets.py
> +    def delete(self, uuid):
no type hints

2021-11-16 18:23 UTC, SteveMcGrath commented on tenable/io/v3/assets.py
> +    def details(self, obj_id):
no type hints

2021-11-16 18:23 UTC, SteveMcGrath commented on tenable/io/v3/assets.py
> +        check_obj_id = self._check("obj_id", obj_id, str)
_check usage should be deprecated

2021-11-16 18:23 UTC, SteveMcGrath commented on tenable/io/v3/assets.py
> +    """
An attribute `_path` should be defined on the class with the string value of "v3/assets".  This refers to the base path that this resource is on.

2021-11-16 18:23 UTC, SteveMcGrath commented on tenable/io/v3/assets.py
> +    """
An attribute `_conv_json` should be defined with a bool value of `True`.  This informs the HTTP method methods to attempt automatic conversion of json responses.

2021-11-16 18:23 UTC, SteveMcGrath commented on tenable/io/v3/assets.py
> +        return self._api.get("assets").json()["assets"]
Should use `self._get()['assets']` instead.

2021-11-16 18:23 UTC, SteveMcGrath commented on tenable/io/v3/assets.py
> +        return self._api.get(f"assets/{check_obj_id}").json()
should use `self._get(obj_id)` instead.

2021-11-16 18:23 UTC, SteveMcGrath commented on tenable/io/v3/assets.py
> +    def assign_tags(self, action, assets, tags):
no type hints

2021-11-16 18:23 UTC, SteveMcGrath commented on tenable/io/v3/assets.py
> +    def asset_import(self, source, *assets):
no type hints

2021-11-16 18:23 UTC, SteveMcGrath commented on tenable/io/v3/assets.py
> +        ).json()["asset_import_job_uuid"]
will the API endpoint path change here in v3?  Also we shouldn't use check.

2021-11-16 18:23 UTC, SteveMcGrath commented on tenable/io/v3/assets.py
> +    def import_job_details(self, uuid):
type hinting

2021-11-16 18:23 UTC, SteveMcGrath commented on tenable/io/v3/assets.py
> +        return self._api.get(f"import/asset-jobs/{check_uuid}").json()
shouldn't use check.

2021-11-16 18:23 UTC, SteveMcGrath commented on tenable/io/v3/assets.py
> +    def move_assets(self, source, destination, targets):
type hinting

2021-11-16 18:23 UTC, SteveMcGrath commented on tenable/io/v3/assets.py
> +        }
check usage should be deprecated

2021-11-16 18:23 UTC, SteveMcGrath commented on tenable/io/v3/assets.py
> +                "source": self._check("source", source, str),
_check usage should be deprecated

2021-11-26 11:54 UTC, ngaglani-tenable commented
The changes have been updated in PR #12 . Hence, closing this PR.

2021-11-26 11:54 UTC, closed without merging