users endpoint version 3
dhvanilshah-tenable/pyTenable pull request #4
Opened 2021-11-18 15:19 UTC by sahils-tenable

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:
* Python Version(s) Tested:
* Tenable.sc version (if necessary):

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2021-11-19 19:00 UTC, tomeara requested changes

2021-11-22 16:38 UTC, sahils-tenable commented on tests/io/v3/vm/test_users.py
> +                      "uuid_id": "73cc516b-51d0-445a-8e0d-6f618455770e",
uuid_id => is being described as uuid for the user. 

--> https://developer.tenable.com/reference#users-details

2021-11-22 21:42 UTC, tomeara requested changes
Need to remove one of the calls. Added some more comments

2021-11-22 21:42 UTC, tomeara commented on tenable/io/v3/vm/users.py
> +    def impersonate(self, name: str) -> None:
We should leave this out

2021-11-22 21:42 UTC, tomeara commented on tests/io/v3/vm/test_users.py
> +                      "group_uuids": [
Let's go with `group_ids`

2021-11-22 21:42 UTC, tomeara commented on tests/io/v3/vm/test_users.py
> +                      "uuid_id": "73cc516b-51d0-445a-8e0d-6f618455770e"
we should either rename this, or leave it out

2021-11-24 02:05 UTC, tomeara approved these changes
Looks good to me!

2021-11-24 07:41 UTC, merged