Scanner_groups version 3
dhvanilshah-tenable/pyTenable pull request #40
Opened 2021-12-16 07:00 UTC by sahils-tenable

#Description

This PR consists of all the changes for version 3 endpoints and automated tests.
** Not included the search actions implementations and its endpoint.

2021-12-16 12:16 UTC, harshshah-tenable commented on tests/io/v3/vm/scanner_groups/test_scanner_group_api.py
> +    name = 'sahil_test3'
Please update the name with an appropriate test value at all instances.

2021-12-16 12:16 UTC, harshshah-tenable commented on tenable/io/v3/vm/scanner_groups/schema.py
> +    type = fields.Str(validate=v.OneOf(['load_balancing']))
I believe the default value is `load_balancing`, it supports other values as well as per description here https://developer.tenable.com/reference#scanner-groups-create

2021-12-16 13:02 UTC, harshshah-tenable commented on tenable/io/v3/vm/scanner_groups/schema.py
> +    type = fields.Str(validate=v.OneOf(['load_balancing']))
It is the only supported value confirmed with Sahil

2021-12-21 21:03 UTC, tomeara requested changes

2021-12-21 21:03 UTC, tomeara commented on tests/io/v3/vm/scanner_groups/test_scanner_group_api.py
> +    'creation_date': 1639386455,
All datetime should be ISO8601

2021-12-22 14:50 UTC, tomeara commented on tests/io/v3/vm/scanner_groups/test_scanner_group_api.py
> +        "creation_date": '2020-07-10 15:00:00.000',
I think we will want to include the timezone format for this

2021-12-24 15:36 UTC, dhvanilshah-tenable approved these changes

2021-12-24 15:36 UTC, dhvanilshah-tenable commented on tenable/io/v3/vm/scanner_groups/api.py
> +    '''
'''
    This class contains methods related to Scanner Groups API
    '''

2021-12-24 15:36 UTC, dhvanilshah-tenable commented on tenable/io/v3/vm/scanner_groups/api.py
> +    _schema = ScannerGroupsSchema()
Could you please update name to ScannerGroupSchema for consistency.

2021-12-24 15:36 UTC, dhvanilshah-tenable commented on tests/io/v3/vm/scanner_groups/test_scanner_group_api.py
> +        "creation_date": '2019-12-31T20:50:23.635Z',
Can you replace double quotes with single quotes?

2021-12-24 15:36 UTC, dhvanilshah-tenable commented on tests/io/v3/vm/scanner_groups/test_scanner_group_api.py
> +SCANNER_G_DETAILS = {
Could you please write the constants name as complete. It will be easier for others.

2021-12-24 15:36 UTC, dhvanilshah-tenable commented on tests/io/v3/vm/scanner_groups/test_scanner_group_api.py
> +SCANNER_LIST_ROU_RESP = [
Could you please write the constants name as complete.

2021-12-24 15:36 UTC, dhvanilshah-tenable commented on tests/io/v3/vm/scanner_groups/test_scanner_group_api.py
> +    assert isinstance(data, list)
Please also verify some of the keys and values obtained from the data.

2021-12-29 15:19 UTC, tomeara approved these changes

2021-12-30 14:04 UTC, merged