mssp/accounts
dhvanilshah-tenable/pyTenable pull request #47
Opened 2021-12-27 12:10 UTC by parvdesai-tenable

2021-12-30 05:37 UTC, dhvanilshah-tenable approved these changes

2021-12-30 05:37 UTC, dhvanilshah-tenable commented on tenable/io/v3/__init__.py
> +        :doc:`tenable.io v3 Managed Security Service Provider APIs
tenable.io => Tenable.io for consistency with other modules.

2021-12-30 05:37 UTC, dhvanilshah-tenable commented on tenable/io/v3/mssp/__init__.py
> +        :doc:`Accounts API <accounts>`
Tenable.io v3 Accounts APIs <accounts>.

2022-01-03 06:34 UTC, harshshah-tenable approved these changes

2022-02-24 13:54 UTC, alpesh-te requested changes
Minor fix and it has only search API, looks good to me!

2022-02-24 13:54 UTC, alpesh-te commented on tenable/io/v3/mssp/accounts/api.py
> +                If ``return_json`` was set to ``True``, then a response
Update docstring.

2022-03-10 10:48 UTC, alpesh-te commented on tenable/io/v3/mssp/accounts/api.py
> +                If ``return_json`` was set to ``True``, then a response
Addresed

2022-03-10 11:05 UTC, alpesh-te approved these changes
LGTM!

2022-03-10 11:08 UTC, merged