Add support for Audit Log module in Tenable.io v3
dhvanilshah-tenable/pyTenable pull request #61
Opened 2022-01-10 10:42 UTC by dhvanilshah-tenable

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:
* Python Version(s) Tested:
* Tenable.sc version (if necessary):

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2022-01-10 11:48 UTC, harshshah-tenable approved these changes

2022-01-27 08:37 UTC, parvdesai-tenable approved these changes

2022-02-23 11:46 UTC, Mangusingh-te requested changes

2022-02-23 11:46 UTC, Mangusingh-te commented on tenable/io/v3/vm/audit_log/api.py
> +The following methods allow for interaction into the Tenable.io
```suggestion
The following methods allow interaction withTenable.io
```

2022-02-23 11:46 UTC, Mangusingh-te commented on tenable/io/v3/vm/audit_log/api.py
> +            return_resp (bool, optional):
Update docstring.

2022-02-23 11:46 UTC, Mangusingh-te commented on tenable/io/v3/vm/audit_log/api.py
> +                If ``return_json`` was set to ``True``, then a response
Update docstring.

2022-02-23 11:46 UTC, Mangusingh-te commented on tests/io/v3/vm/audit_log/test_audit_log_api.py
> +    assert len(event_list) == api_res['pagination']['total']
Rewrite it in pythonic way.

2022-03-11 04:54 UTC, alpesh-te commented on tenable/io/v3/vm/audit_log/api.py
> +            return_resp (bool, optional):
Addressed

2022-03-11 04:54 UTC, alpesh-te commented on tests/io/v3/vm/audit_log/test_audit_log_api.py
> +    assert len(event_list) == api_res['pagination']['total']
Addressed

2022-03-11 04:55 UTC, alpesh-te commented on tenable/io/v3/vm/audit_log/api.py
> +                If ``return_json`` was set to ``True``, then a response
Addressed

2022-03-11 05:00 UTC, alpesh-te approved these changes
LGTM!

2022-03-11 05:01 UTC, merged