vm/scanners
dhvanilshah-tenable/pyTenable pull request #65
Opened 2022-01-17 05:34 UTC by harshshah-tenable

# Updated following actions for Scanners API:
- search()
- get_permissions()
- edit_permissions()

Other structure and schema related changes are also covered in this PR

ToDo: 
- Validate search method and tests once search WUG PR is merged
- Validate get_permissions() and edit_permissions() 
- update allowed_scanners() once policies and editors PR is merged

2022-02-09 13:58 UTC, ngaglani-tenable commented on tenable/io/v3/vm/scanners/api.py
> +            ... pprint(scanner)
```suggestion
            >>> pprint(scanner)
```

2022-02-09 14:00 UTC, ngaglani-tenable commented on tests/io/v3/vm/scanners/test_scanners_api.py
> +    assert len(event_list) == api_response['pagination']['total']
```suggestion
    scnners_list = []
    for scanner in iterator:
        scnners_list.append(scanner)
    assert len(scnners_list) == api_response['pagination']['total']
```

2022-02-09 14:01 UTC, ngaglani-tenable commented on tenable/io/v3/vm/scanners/api.py
Class docstring is missing.

2022-02-28 14:36 UTC, alpesh-te requested changes
Minor fixes!

2022-02-28 14:36 UTC, alpesh-te commented on tests/io/v3/vm/scanners/test_scanners_api.py
> +    assert len(list(iterator)) == api_response['pagination']['total']
Get rid of loop.

2022-03-11 07:43 UTC, alpesh-te commented on tests/io/v3/vm/scanners/test_scanners_api.py
> +    assert len(list(iterator)) == api_response['pagination']['total']
It is already fixed

2022-03-11 07:43 UTC, alpesh-te approved these changes

2022-03-11 07:48 UTC, merged