vm/plugins
dhvanilshah-tenable/pyTenable pull request #67
Opened 2022-01-17 09:26 UTC by parvdesai-tenable

2022-02-01 11:19 UTC, ngaglani-tenable commented on tenable/io/v3/vm/plugins/api.py
> +                the :py:meth:`tio.v3.vm.filters.families_filters()`
```suggestion
                the :py:meth:`tio.v3.definitions.vm.plugin_families()`
```

2022-02-01 11:21 UTC, ngaglani-tenable commented on tenable/io/v3/vm/plugins/api.py
>          :devportal:`plugins: family-details plugins-family-details>`
Typing is missing from `family_id` parameter's description in docstring.

2022-02-01 11:24 UTC, ngaglani-tenable commented on tenable/io/v3/vm/plugins/api.py
> +    def search_families(self, **kwargs) -> Union[CSVChunkIterator,
Can we alphabetize the methods?

2022-02-01 11:27 UTC, ngaglani-tenable commented on tenable/io/v3/vm/plugins/api.py
>          :devportal:`plugins: plugin-details <plugins-plugin-details>`
Return type should be Dict in docstring.

2022-02-01 11:28 UTC, ngaglani-tenable commented on tenable/io/v3/vm/plugins/api.py
> +                the :py:meth:`tio.v3.vm.filters.plugins_filters()`
```suggestion
                the :py:meth:`tio.v3.definitions.vm.plugins()`
```

2022-02-02 19:07 UTC, harshshah-tenable commented on tests/io/v3/vm/plugins/objects.py
> +    "attributes": [
Please update `"` -> `'`

2022-02-09 12:32 UTC, ngaglani-tenable approved these changes

2022-02-23 15:04 UTC, Mangusingh-te requested changes

2022-02-23 15:04 UTC, Mangusingh-te commented on tenable/io/v3/vm/plugins/api.py
> +            return_resp (bool, optional):
Update docstring.

2022-02-23 15:04 UTC, Mangusingh-te commented on tenable/io/v3/vm/plugins/api.py
> +                If ``return_json`` was set to ``True``, then a response
Update docstring.

2022-02-23 15:04 UTC, Mangusingh-te commented on tenable/io/v3/vm/plugins/api.py
> +            return_resp (bool, optional):
Update docstring.

2022-02-23 15:04 UTC, Mangusingh-te commented on tenable/io/v3/vm/plugins/api.py
> +                If ``return_json`` was set to ``True``, then a response
update docstring.

2022-03-11 11:12 UTC, alpesh-te commented on tenable/io/v3/vm/plugins/api.py
> +                If ``return_json`` was set to ``True``, then a response
Addressed

2022-03-11 11:12 UTC, alpesh-te commented on tenable/io/v3/vm/plugins/api.py
> +            return_resp (bool, optional):
Addressed

2022-03-11 11:12 UTC, alpesh-te commented on tenable/io/v3/vm/plugins/api.py
> +                If ``return_json`` was set to ``True``, then a response
Addressed

2022-03-11 11:12 UTC, alpesh-te approved these changes
LGTM!

2022-03-11 11:13 UTC, merged