vm/networks (search method)
dhvanilshah-tenable/pyTenable pull request #72
Opened 2022-01-19 18:23 UTC by harshshah-tenable

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:
* Python Version(s) Tested:
* Tenable.sc version (if necessary):

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2022-02-01 12:04 UTC, ngaglani-tenable commented on tests/io/v3/vm/networks/test_networks_api.py
> +    event_list = []
```suggestion
    network_list = []
    for network in iterator:
        network_list.append(event)
    assert len(network_list) == api_response['pagination']['total']
```

2022-02-01 12:05 UTC, ngaglani-tenable commented on tests/io/v3/vm/networks/test_networks_api.py
> +    assert len(event_list) == api_response['pagination']['total']
```suggestion
    network_list = []
    for network in iterator:
        network_list.append(event)
    assert len(network_list) == api_response['pagination']['total']
```

2022-02-01 12:12 UTC, ngaglani-tenable approved these changes

2022-02-24 08:36 UTC, Mangusingh-te requested changes

2022-02-24 08:36 UTC, Mangusingh-te commented on tenable/io/v3/vm/networks/api.py
> +            return_resp (bool, optional):
Update docstring.

2022-02-24 08:36 UTC, Mangusingh-te commented on tenable/io/v3/vm/networks/api.py
> +                If ``return_json`` was set to ``True``, then a response
Update docstring.

2022-02-24 08:36 UTC, Mangusingh-te commented on tests/io/v3/vm/networks/test_networks_api.py
> +    assert len(networks_list) == api_response['pagination']['total']
Rewrite it to get rid of loop.

2022-02-28 12:06 UTC, harshshah-tenable commented on tests/io/v3/vm/networks/test_networks_api.py
> +    assert len(networks_list) == api_response['pagination']['total']
Updated

2022-02-28 12:06 UTC, harshshah-tenable commented on tenable/io/v3/vm/networks/api.py
> +                If ``return_json`` was set to ``True``, then a response
Updated

2022-02-28 12:06 UTC, harshshah-tenable commented on tenable/io/v3/vm/networks/api.py
> +            return_resp (bool, optional):
Updated

2022-03-17 07:00 UTC, merged