Scanner-Groups: Added search endpoint support
dhvanilshah-tenable/pyTenable pull request #75
Opened 2022-01-21 11:50 UTC by sahils-tenable

# Description

Added support for search endpoints and its tests

2022-02-01 08:29 UTC, harshshah-tenable commented on tenable/io/v3/vm/scanner_groups/api.py
> +                endpoint to get more details.
Please add the respective filter/definition method in docstring.

2022-02-02 05:14 UTC, milanaghera-tenable approved these changes

2022-02-09 13:45 UTC, ngaglani-tenable commented on tenable/io/v3/vm/scanner_groups/api.py
> -            :obj:`dict`:
Should we revert this to `dict`?

2022-02-10 09:34 UTC, sahils-tenable commented on tenable/io/v3/vm/scanner_groups/api.py
> -            :obj:`dict`:
we will do this at final stage for all endpoints

2022-02-28 05:35 UTC, alpesh-te requested changes
Minor fixes!

2022-02-28 05:35 UTC, alpesh-te commented on tenable/io/v3/vm/scanner_groups/api.py
> +                If ``return_json`` was set to ``True``, then a response
Update docstring.

2022-02-28 05:35 UTC, alpesh-te commented on tests/io/v3/vm/scanner_groups/test_scanner_group_api.py
> +    assert len(event_list) == api_response['pagination']['total']
get rid of loop.

2022-03-17 06:41 UTC, alpesh-te commented on tenable/io/v3/vm/scanner_groups/api.py
> +                If ``return_json`` was set to ``True``, then a response
Addressed

2022-03-17 06:41 UTC, alpesh-te commented on tests/io/v3/vm/scanner_groups/test_scanner_group_api.py
> +    assert len(event_list) == api_response['pagination']['total']
Addressed

2022-03-17 06:46 UTC, merged