Users/search_support
dhvanilshah-tenable/pyTenable pull request #78
Opened 2022-01-27 14:07 UTC by sahils-tenable

Added support for search endpoint

2022-01-27 17:03 UTC, harshshah-tenable approved these changes

2022-02-09 15:17 UTC, ngaglani-tenable commented on tenable/io/v3/users/api.py
> +        Retrieves the users data.
Update the description as per the latest one.

2022-02-25 13:33 UTC, alpesh-te requested changes
Minor fixes, other than that LGMT

2022-02-25 13:33 UTC, alpesh-te commented on tests/io/v3/users/test_users_api.py
> +    assert len(event_list) == api_response['pagination']['total']
Rewrite it to get rid of loop.

2022-02-25 13:33 UTC, alpesh-te commented on tenable/io/v3/users/api.py
> +                If ``return_json`` was set to ``True``, then a response
Do string update

2022-03-16 13:19 UTC, alpesh-te commented on tenable/io/v3/users/api.py
> +                If ``return_json`` was set to ``True``, then a response
Addressed

2022-03-16 13:19 UTC, alpesh-te commented on tests/io/v3/users/test_users_api.py
> +    assert len(event_list) == api_response['pagination']['total']
Addressed

2022-03-16 13:22 UTC, alpesh-te commented on tenable/io/v3/users/api.py
> +        Retrieves the users data.
Addressed

2022-03-16 13:23 UTC, alpesh-te approved these changes
LGMT

2022-03-16 13:28 UTC, merged