vm/credentials (search method)
dhvanilshah-tenable/pyTenable pull request #79
Opened 2022-01-27 15:31 UTC by harshshah-tenable

Search method changes for Credentials endpoint

2022-02-01 09:42 UTC, ngaglani-tenable commented on tenable/io/v3/vm/credentials/api.py
> +            ... tio.v3.vm.credentials.create('SSH Account', 'SSH',
```suggestion
            >>> tio.v3.vm.credentials.create('SSH Account', 'SSH',
```

2022-02-01 09:43 UTC, ngaglani-tenable commented on tenable/io/v3/vm/credentials/api.py
> +            ... tio.v3.vm.credentials.edit(cred_id,
```suggestion
            >>> tio.v3.vm.credentials.edit(cred_id,
```

2022-02-01 10:06 UTC, ngaglani-tenable commented on tenable/io/v3/vm/credentials/api.py
> +            ... cred = tio.v3.vm.credentials.details(cred_id)
```suggestion
            >>> cred = tio.v3.vm.credentials.details(cred_id
```

2022-02-01 10:09 UTC, ngaglani-tenable commented on tenable/io/v3/vm/credentials/api.py
> +            ... cred = tio.v3.vm.credentials.delete(cred_id)
```suggestion
            >>> cred = tio.v3.vm.credentials.delete(cred_id)
```

2022-02-01 10:12 UTC, ngaglani-tenable commented
`edit` and `search` Methods are not alphabetized.

2022-02-01 10:15 UTC, ngaglani-tenable commented
Format the parameters in `create` and `edit` methods.

2022-02-01 10:52 UTC, ngaglani-tenable commented on tests/io/v3/vm/credentials/test_credentials_api.py
> +    assert len(event_list) == api_res['pagination']['total']
```suggestion
    credential_list = []
    for credential in iterator:
        credential_list.append(credential)
    assert len(credential_list) == api_res['pagination']['total']
```

2022-02-01 10:53 UTC, ngaglani-tenable approved these changes

2022-02-08 14:18 UTC, dhvanilshah-tenable commented on tenable/io/v3/vm/credentials/api.py
> +                For Credentaials endpoint respective definitions endpoint
Typo: Credentaials  -> Credentials

2022-02-24 14:23 UTC, alpesh-te requested changes
Minor fixes, other than that LGTM

2022-02-24 14:23 UTC, alpesh-te commented on tests/io/v3/vm/credentials/test_credentials_api.py
> +    assert len(credential_list) == api_res['pagination']['total']
Rewrite it to get rid of loop.

2022-02-24 14:23 UTC, alpesh-te commented on tenable/io/v3/vm/credentials/api.py
> +                If ``return_json`` was set to ``True``, then a response
Update docstring.

2022-02-25 13:26 UTC, alpesh-te requested changes
Normal fixes other than that LGTM!

2022-02-25 13:26 UTC, alpesh-te commented on tenable/io/v3/vm/credentials/api.py
> +                If ``return_json`` was set to ``True``, then a response
Update docstring.

2022-02-25 13:28 UTC, alpesh-te requested changes
Minor fix, other than that LGMT

2022-02-25 13:28 UTC, alpesh-te commented on tests/io/v3/vm/credentials/test_credentials_api.py
> +    assert len(list(iterator)) == api_res['pagination']['total']
Rewrite it to get rid of loop.

2022-03-17 06:09 UTC, alpesh-te approved these changes

2022-03-17 06:10 UTC, merged