Search endpoint support, added bulk operation endpoint
dhvanilshah-tenable/pyTenable pull request #80
Opened 2022-01-28 12:32 UTC by milanaghera-tenable

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:
* Python Version(s) Tested:
* Tenable.sc version (if necessary):

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2022-02-01 08:22 UTC, harshshah-tenable reviewed
Unit tests are failing can you please have a look

2022-02-02 18:39 UTC, harshshah-tenable approved these changes

2022-02-08 07:13 UTC, harshshah-tenable approved these changes

2022-02-18 17:51 UTC, alpesh-te requested changes
Need to fix minor things

2022-02-18 17:51 UTC, alpesh-te commented on tenable/io/v3/vm/agents/api.py
> +    def task_status(self, task_id: UUID) -> Dict:
To verifying against confluence, I could not find `taks_status` function here https://confluence.eng.tenable.com/display/PORG/%5BSDK%5D+Agents

2022-02-18 17:51 UTC, alpesh-te commented on tenable/io/v3/vm/agents/api.py
> +    def add_agents_to_network(self, *agent_ids: UUID, **kwargs) -> Dict:
To verifying against confluence, I could not find **add_agents_to_network** function here https://confluence.eng.tenable.com/display/PORG/%5BSDK%5D+Agents

2022-02-18 17:51 UTC, alpesh-te commented on tenable/io/v3/vm/agents/api.py
> +    def remove_agent_from_network(self, *agent_ids: UUID, **kwargs) -> Dict:
To verifying against confluence, I could not find **remove_agent_from_network** function here https://confluence.eng.tenable.com/display/PORG/%5BSDK%5D+Agents

2022-02-18 17:51 UTC, alpesh-te commented on tenable/io/v3/vm/agents/api.py
> +    def send_instructuion_to_agent(self,
To verifying against confluence, I could not find **send_instructuion_to_agent** function here https://confluence.eng.tenable.com/display/PORG/%5BSDK%5D+Agents

2022-02-18 17:51 UTC, alpesh-te commented on tests/io/v3/vm/agents/test_agents_schema.py
> +def test_agent_schema():
we should follow naming convention same everywhere `test_agent_schema` to `test_agents_schema`. Please make sure changes on related files

2022-02-18 17:51 UTC, alpesh-te commented on tests/io/v3/vm/agents/test_agents_api.py
> +    assert len(values_list) == test_response['pagination']['total']
can be rewritten in pythonic way to get rid of loop.

2022-02-22 05:11 UTC, milanaghera-tenable commented on tenable/io/v3/vm/agents/api.py
> +    def task_status(self, task_id: UUID) -> Dict:
@alpesh-te `task_status` method is related to the bulk operation endpoint that we have included in the agent's module based on @tomeara's suggestion. for more details please refer to the [agent bulk operation confluence page](https://confluence.eng.tenable.com/display/PORG/%5BSDK%5D+Agent+Bulk+Operation).

2022-02-22 05:58 UTC, milanaghera-tenable commented on tenable/io/v3/vm/agents/api.py
> +    def add_agents_to_network(self, *agent_ids: UUID, **kwargs) -> Dict:
@alpesh-te `add_agents_to_network `method is related to the bulk operation endpoint that we have included in the agent's module based on @tomeara's suggestion. for more details please refer to the [agent bulk operation confluence page](https://confluence.eng.tenable.com/display/PORG/%5BSDK%5D+Agent+Bulk+Operation).

2022-02-22 05:59 UTC, milanaghera-tenable commented on tenable/io/v3/vm/agents/api.py
> +    def remove_agent_from_network(self, *agent_ids: UUID, **kwargs) -> Dict:
@alpesh-te `remove_agent_from_network `method is related to the bulk operation endpoint that we have included in the agent's module based on @tomeara's suggestion. for more details please refer to the [agent bulk operation confluence page](https://confluence.eng.tenable.com/display/PORG/%5BSDK%5D+Agent+Bulk+Operation).

2022-02-22 06:00 UTC, milanaghera-tenable commented on tenable/io/v3/vm/agents/api.py
> +    def send_instructuion_to_agent(self,
@alpesh-te `send_instructuion_to_agent `method is related to the bulk operation endpoint that we have included in the agent's module based on @tomeara's suggestion. for more details please refer to the [agent bulk operation confluence page](https://confluence.eng.tenable.com/display/PORG/%5BSDK%5D+Agent+Bulk+Operation).

2022-02-25 07:34 UTC, milanaghera-tenable commented on tests/io/v3/vm/agents/test_agents_api.py
> +    assert len(values_list) == test_response['pagination']['total']
Resolved.

2022-03-08 11:39 UTC, alpesh-te approved these changes
LGTM

2022-03-08 12:06 UTC, merged