Added schema validation and update base API endpoint
dhvanilshah-tenable/pyTenable pull request #85
Opened 2022-01-31 10:40 UTC by milanaghera-tenable

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:
* Python Version(s) Tested:
* Tenable.sc version (if necessary):

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2022-02-02 18:01 UTC, harshshah-tenable approved these changes

2022-02-03 12:30 UTC, dhvanilshah-tenable approved these changes

2022-02-03 19:13 UTC, ngaglani-tenable commented on tenable/io/v3/vm/agent_config/schema.py
> +    def pre_searilization(self, data, **kwarg):
```suggestion
    def pre_serialization(self, data, **kwarg):
```

2022-02-03 19:16 UTC, ngaglani-tenable commented on tests/io/v3/vm/agent_config/test_agent_config_api.py
> +Test cases for Agent
```suggestion
Test cases for Agent Config
```

2022-02-03 19:19 UTC, ngaglani-tenable commented on tenable/io/v3/vm/agent_config/api.py
>              software_update (bool, optional):
Can we alphabetize the arguments in docstring?

2022-02-03 19:21 UTC, ngaglani-tenable commented on tenable/io/v3/vm/agent_config/api.py
> +    def edit(self,
Method definitions can be alphabetized.

2022-02-03 19:21 UTC, ngaglani-tenable approved these changes

2022-02-04 05:31 UTC, milanaghera-tenable commented on tenable/io/v3/vm/agent_config/schema.py
> +    def pre_searilization(self, data, **kwarg):
done.

2022-02-16 11:25 UTC, Mangusingh-te commented
@milanaghera-tenable Add test-cases covering invalid/unsupported data passed to api methods as well as to schema serialization/deserialization. Also did docs needs to be updated too, as part of this PR ?

2022-02-16 11:28 UTC, Mangusingh-te commented
@milanaghera-tenable Apart from review comments posted above, code-changes looks okay. Also how failing **snyk** security checks in github be fixed ?

2022-02-16 15:21 UTC, Mangusingh-te requested changes

2022-02-16 15:21 UTC, Mangusingh-te commented on tenable/io/v3/vm/agent_config/api.py
>  class AgentConfigAPI(ExploreBaseEndpoint):
**agent_config** should be renamed as **agents_config** at all possible occurrences(module name, class-name, method-name, imports, test-cases, etc.). The reason being, both endpoints covered in **agents_config** targe configuration of all agents, instead of single agent. Although I know that existing **agents_config** code(prior to v3) has incorrect naming convention.

2022-02-16 15:21 UTC, Mangusingh-te commented on tenable/io/v3/vm/agent_config/api.py
>          :devportal:`agent-config: edit <agent-config-details>`
```suggestion
        :devportal:`agent-config: edit <agent-config-edit>`
```

2022-02-16 15:21 UTC, Mangusingh-te commented on tenable/io/v3/vm/agent_config/api.py
> +        :devportal:`agent-config: details <agent-config-edit>`
```suggestion
        :devportal:`agent-config: details <agent-config-details>`
```

2022-02-16 15:21 UTC, Mangusingh-te commented on tenable/io/v3/vm/agent_config/api.py
> +        payload = self._schema.dump(self._schema.load(payload))
Is it necessary to chain **dump** and **load** calls ? @SteveMcGrath any thoughts on, why this pattern is needed ? Can we get rid of this pattern ?

2022-02-16 15:21 UTC, Mangusingh-te commented on tenable/io/v3/vm/agent_config/schema.py
> +            data['enabled'] = True
Existing **agent-config** [edit](https://github.com/tenable/pyTenable/blob/master/tenable/io/agent_config.py#L64) implementation throws Validation errors, when expiration value is not between 1 and 366. Is this behavior changed intentionally ? Any reason for changing for changing this behavior ?

2022-02-17 04:56 UTC, alpesh-te requested changes
We should add all positive scenario with all combination, I have found one positive test case missing passing below payload. This request serve on frontend.
 
![image](https://user-images.githubusercontent.com/99801648/154407839-80880dac-ff71-4995-a34a-adf025f588e8.png)

2022-02-17 10:22 UTC, harshshah-tenable commented on tenable/io/v3/vm/agent_config/api.py
>  class AgentConfigAPI(ExploreBaseEndpoint):
The reason it was kept as **agent_config** was to stay in harmony with v2 code and the API documentation. @tomeara do you think we should rename it as **agents_config**? If yes this should be reflected in the documentation as well correct **Agent Config** -> **Agents Config**

Or should we update it as **agent_configs** similar to **agent_exclusions** and **agent_groups** in code as well as in documentation?

2022-02-17 12:46 UTC, milanaghera-tenable commented on tenable/io/v3/vm/agent_config/schema.py
> +            data['enabled'] = True
Resolved.

2022-02-17 12:47 UTC, milanaghera-tenable commented on tenable/io/v3/vm/agent_config/api.py
> +        :devportal:`agent-config: details <agent-config-edit>`
Resolved.

2022-02-17 12:47 UTC, milanaghera-tenable commented on tenable/io/v3/vm/agent_config/api.py
>          :devportal:`agent-config: edit <agent-config-details>`
Resolved.

2022-02-23 11:29 UTC, milanaghera-tenable commented on tenable/io/v3/vm/agent_config/api.py
>  class AgentConfigAPI(ExploreBaseEndpoint):
updated the class name to `AgentConfig -> AgentsConfig` and `AgentConfigSchema -> AgentsConfigSchema`

2022-02-23 15:13 UTC, SteveMcGrath commented on tenable/io/v3/vm/agent_config/api.py
> +        payload = self._schema.dump(self._schema.load(payload))
Load converts from the data fed by the caller to the object-native format.

Dump converts from the object-native format to the expected format that the API expects.

Yes they are both needed, in that order.

2022-03-08 11:38 UTC, merged