added Search and Details endpoint for agent groups
dhvanilshah-tenable/pyTenable pull request #86
Opened 2022-01-31 17:29 UTC by milanaghera-tenable

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:
* Python Version(s) Tested:
* Tenable.sc version (if necessary):

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2022-02-03 19:05 UTC, ngaglani-tenable approved these changes

2022-02-03 19:30 UTC, ngaglani-tenable approved these changes

2022-02-18 04:17 UTC, alpesh-te requested changes
I have given few comments

2022-02-18 04:17 UTC, alpesh-te commented on tests/io/v3/vm/agent_groups/test_agent_groups_schema.py
>  from tenable.io.v3.vm.agent_groups.schema import AgentGroupSchema
There should be name consistency across the module `AgentGroupSchema` should be `AgentGroupsSchema`

2022-02-18 04:17 UTC, alpesh-te commented on tenable/io/v3/vm/agent_groups/schema.py
> +class AgentGroupFilterSchema(ParseFilterSchema):
There should be name consistency across the module  `AgentGroupFilterSchema` should be `AgentGroupsFilterSchema`

2022-02-18 04:17 UTC, alpesh-te commented on tests/io/v3/vm/agent_groups/test_agent_groups_schema.py
> +        'filter_type': 'and',
Can you please give me more context about `filter_type` as payload? I couldn't find here https://confluence.eng.tenable.com/pages/viewpage.action?spaceKey=PORG&title=%5BSDK%5D+Agent+Groups

2022-02-18 04:17 UTC, alpesh-te commented on tests/io/v3/vm/agent_groups/test_agent_groups_schema.py
> +        'wildcard': 'IYKKQIGOBWXUXOZIBURFENPNMGZOSWBUKVCD',
Can you please give me more context about `wildcard` as payload? I couldn't find here https://confluence.eng.tenable.com/pages/viewpage.action?spaceKey=PORG&title=%5BSDK%5D+Agent+Groups

2022-02-18 04:17 UTC, alpesh-te commented on tests/io/v3/vm/agent_groups/test_agent_groups_schema.py
> +        'wildcard_fields': ['name']
Can you please give me more context about `wildcard_fields` as payload? I couldn't find here https://confluence.eng.tenable.com/pages/viewpage.action?spaceKey=PORG&title=%5BSDK%5D+Agent+Groups

2022-02-18 04:17 UTC, alpesh-te commented on tests/io/v3/vm/agent_groups/test_agent_groups_api.py
> +            'operator': 'date-eq',
`date-eq` operator doesn't match with API Specification doc https://confluence.eng.tenable.com/display/UW/UW+API+Specification

2022-02-18 12:27 UTC, alpesh-te commented on tests/io/v3/vm/agent_groups/test_agent_groups_api.py
> +    assert len(exclusions_list) == test_response['pagination']['total']
Refactor above code to get rid of loop

2022-02-22 06:12 UTC, milanaghera-tenable commented on tests/io/v3/vm/agent_groups/test_agent_groups_schema.py
> +        'filter_type': 'and',
@alpesh-te filter_type is a part of the `send_instruction_to_agents_in_group` method's request body and this particular method is related to agent bulk operation API also based on @tomeara 's suggestion we have included this endpoint in the agent_groups module. for more details please refer to the [agent bulk operation confluence page](https://confluence.eng.tenable.com/display/PORG/%5BSDK%5D+Agent+Bulk+Operation).

2022-02-22 06:14 UTC, milanaghera-tenable commented on tests/io/v3/vm/agent_groups/test_agent_groups_schema.py
> +        'wildcard': 'IYKKQIGOBWXUXOZIBURFENPNMGZOSWBUKVCD',
@alpesh-te `wildcard `is a part of the `send_instruction_to_agents_in_group `method's request body. for more details please refer to the [agent bulk operation confluence page](https://confluence.eng.tenable.com/display/PORG/%5BSDK%5D+Agent+Bulk+Operation).

2022-02-22 06:15 UTC, milanaghera-tenable commented on tests/io/v3/vm/agent_groups/test_agent_groups_schema.py
> +        'wildcard_fields': ['name']
@alpesh-te `wildcard_fields` is a part of the `send_instruction_to_agents_in_group` method's request body. for more details please refer to the [agent bulk operation confluence page](https://confluence.eng.tenable.com/display/PORG/%5BSDK%5D+Agent+Bulk+Operation).

2022-02-28 11:17 UTC, milanaghera-tenable commented on tests/io/v3/vm/agent_groups/test_agent_groups_schema.py
>  from tenable.io.v3.vm.agent_groups.schema import AgentGroupSchema
@alpesh-te As per our discussion on call, will keep the schema name as it is.

2022-02-28 11:18 UTC, milanaghera-tenable commented on tenable/io/v3/vm/agent_groups/schema.py
> +class AgentGroupFilterSchema(ParseFilterSchema):
@alpesh-te similar to AgentGroupSchema, will keep the AgentGroupFilterSchema name as it is.

2022-02-28 11:22 UTC, milanaghera-tenable commented on tests/io/v3/vm/agent_groups/test_agent_groups_api.py
> +            'operator': 'date-eq',
pre-existing operators were used as filters in this endpoint and more information can be found in ref link : https://jira.eng.tenable.com/browse/IN-582?focusedCommentId=1528634&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-1528634

2022-03-08 05:13 UTC, alpesh-te approved these changes
LGTM!

2022-03-08 05:14 UTC, merged