added search support
dhvanilshah-tenable/pyTenable pull request #90
Opened 2022-02-09 13:08 UTC by sahils-tenable

# Description

Added support for search endpoint.
- needs to be merged in iterator_migration PR

2022-02-21 13:41 UTC, Mangusingh-te requested changes
@sahils-tenable [Specs](https://confluence.eng.tenable.com/pages/viewpage.action?pageId=184630139) implemented by this PR, mentions **next** token to be passed in request body for **POST /api/v3/was/folders/search** endpoint. But it looks like it isn't passed in request body while iterating over search results. Can you make sure implementation adheres to specs mentioned in confluence doc.

2022-02-21 13:41 UTC, Mangusingh-te commented on tenable/io/v3/was/folders/api.py
> +            return_resp (bool, optional):
Update docstring as mentioned at https://github.com/dhvanilshah-tenable/pyTenable/pull/92/files#r808839795.

2022-02-21 13:41 UTC, Mangusingh-te commented on tenable/io/v3/was/folders/api.py
> +                If ``return_json`` was set to ``True``, then a response
```suggestion
                If ``return_json`` is set to ``True``, then a response
```

2022-02-21 13:41 UTC, Mangusingh-te commented on tenable/io/v3/was/folders/api.py
> +                object is instead returned instead of an iterable.
```suggestion
                object is returned instead of an iterable.
```

2022-02-21 13:41 UTC, Mangusingh-te commented on tests/io/v3/was/folders/test_folders_api.py
> +    Test the search method
```suggestion
    Test search method
```

2022-02-21 13:41 UTC, Mangusingh-te commented on tests/io/v3/was/folders/test_folders_api.py
> +    assert len(event_list) == api_response['pagination']['total']
Get rid of loop.

2022-04-13 09:15 UTC, MitaliUpadhyay commented
> @sahils-tenable [Specs](https://confluence.eng.tenable.com/pages/viewpage.action?pageId=184630139) implemented by this PR, mentions **next** token to be passed in request body for **POST /api/v3/was/folders/search** endpoint. But it looks like it isn't passed in request body while iterating over search results. Can you make sure implementation adheres to specs mentioned in confluence doc.

I have just checked [Specs](https://confluence.eng.tenable.com/pages/viewpage.action?pageId=184630139) document. **next** token is no more mentioned in latest version of this document. (i.e. it was there in earlier versions but removed from the latest version.) Also I checked [back-end PR](https://github.eng.tenable.com/Product/service-was-api/pull/2003/files) , **next** token is not present in scala script changes of this PR.

2022-04-19 08:20 UTC, MitaliUpadhyay commented
@alpesh-te, please close this PR as https://github.com/alpesh-te/pyTenable/pull/10 is created for these script changes.

2022-04-19 10:00 UTC, merged